aichat/urls.py
from django.contrib import admin
from django.urls import path 
from . import views

app_name = 'chatbot_project' 

urlpatterns = [
    #path('admin/', views.index,name = 'index'),
    path('', views.index,name='index'),
    path('home/', views.chatBot,name='chatBot')
]

carts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),

    path('checkout/', views.checkout, name='checkout')
]

myProject/urls.py
from django.contrib import admin
from django.urls import path, include
from myProject import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('chat/', include(('aichat.urls','aichat'),namespace = 'chatbot_project')),
    path('home/', include(('aichat.urls','aichat'),namespace = 'chatbot_project2')),
    path('orders/', include('orders.urls')),    
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/alerts.html
{% if messages %}

    {% for message in messages %}
    <div id="message" class="container">
    <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %} role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
        {{ message }}
    </div>
    </div>
    {% endfor %}

{% endif %}

templates/includes/dashboard_sidebar.html
<aside class="col-md-3">
    <!--   SIDEBAR   -->
    <ul class="list-group">
      <a class="list-group-item {% if '/accounts/' == request.path %}active{% endif %}" href="{% url 'dashboard' %}"> Dashboard </a>
      <a class="list-group-item {% if '/my_orders/' in request.path %}active{% endif %}" href="{% url 'my_orders' %}"> My Orders </a>
      <a class="list-group-item {% if '/edit_profile/' in request.path %}active{% endif %}" href="{% url 'edit_profile' %}"> Edit Profile </a>
      <a class="list-group-item {% if '/change_password/' in request.path %}active{% endif %}" href="{% url 'change_password' %}"> Change Password </a>
    </ul>
    <br>
    <a class="btn btn-light btn-block" href="{% url 'logout' %}"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a>
    <!--   SIDEBAR .//END   -->
  </aside>

templates/includes/footer.html
<!-- ========================= FOOTER ========================= -->
<footer class="section-footer border-top">
	<div class="container">
		<section class="footer-bottom border-top row">
			<div class="col-md-2">
				<p class="text-muted"> &copy 2024 Grabdeal </p>
			</div>
			<div class="col-md-8 text-md-center">
				<span  class="px-2">123123</span>
				<span  class="px-2">+123-332-1234</span>
				<span  class="px-2">Street name 123, Avanue abc</span>
			</div>
			<div class="col-md-2 text-md-right text-muted">
				<i class="fab fa-lg fa-cc-visa"></i>
				<i class="fab fa-lg fa-cc-paypal"></i>
				<i class="fab fa-lg fa-cc-mastercard"></i>
			</div>
		</section>
	</div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->

templates/includes/navbar.html
{% load static %}




<header class="section-header">
    <nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTop4">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link"> English </a>

                    </li>
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link"> IND </a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li><a href="#" class="nav-link"> <i class="fa fa-envelope"></i> Email </a></li>
                    <li><a href="#" class="nav-link"> <i class="fa fa-phone"></i> Call us </a></li>
                </ul> <!-- list-inline //  -->
            </div> <!-- navbar-collapse .// -->
        </div> <!-- container //  -->
    </nav>

    <section class="header-main border-bottom">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-2 col-md-3 col-6">
                    <a href="{% url 'home' %}" class="brand-wrap">
                        <img class="logo" src="{% static './images/logo.png' %}">
                    </a> <!-- brand-wrap.// -->
                </div>
                <div class="col-lg col-sm col-md col-6 flex-grow-0">
                    <div class="category-wrap dropdown d-inline-block float-right">
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bars"></i> All category
                        </button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'store' %}">All Products</a>
                            {% for category in links %}
                            <a class="dropdown-item" href="{{ category.get_url }}">{{ category.category_name }}</a>
                            {% endfor %}
                        </div>
                    </div> <!-- category-wrap.// -->
                </div> <!-- col.// -->
                <a href="{% url 'store' %}" class="btn btn-outline-primary">Store</a>
                <div class="col-lg  col-md-6 col-sm-12 col">
                    <form action="{% url 'search' %}" class="search" method="GET">
                        <div class="input-group w-100">
                            <input type="text" class="form-control" style="width:60%;" placeholder="Search" name="keyword">

                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form> <!-- search-wrap .end// -->
                </div> <!-- col.// -->
                <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
                    <div class="d-flex justify-content-end mb-3 mb-lg-0">
                        {% if user.id is not None %}
                        <div class="widget-header">
                            <small class="title text-muted">Welcome {{ user.first_name }}!</small>
                            <div>
                                <a href="{% url 'dashboard' %}">Dashboard</a> <span class="dark-transp"> | </span>
                                <a href="{% url 'logout' %}">Logout</a>
                            </div>
                        </div>
                        {% else %}
                        <div class="widget-header">
                            <small class="title text-muted">Welcome guest!</small>
                            <div>
                                <a href="{% url 'login' %}">Login</a> <span class="dark-transp"> | </span>
                                <a href="{% url 'register' %}">Register</a>
                            </div>
                        </div>
                        {% endif %}
                        <a href="{% url 'cart' %}" class="widget-header pl-3 ml-3">
                            <div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i>
                            </div>
                            <span class="badge badge-pill badge-danger notify">{{ cart_count }}</span>
                        </a>

                        <!-- <a onclick="" href="{% url 'chatbot_project:index' %}" class="widget-header pl-3 ml-3">
                            <div class="icon "><img height="60px" src="{% static 'chatbot_project/images/ai.gif' %}">
                            </div>
                          
                        </a> -->
                        
                    </div> 
                  <!-- widgets-wrap.// -->
                </div> <!-- col.// -->
            </div> <!-- row.// -->
        </div> <!-- container.// -->
    </section> <!-- header-main .// -->




</header> <!-- section-header.// -->
